name: Run tests on MySQL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests-mysql-linux:
    uses: ./.github/workflows/tests-mysql-linux.yml
    with:
      mysql: "8.4"
      python-versions: '["3.10", "3.11", "3.12", "3.13", "3.14", "pypy-3.11"]'
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}

  tests-mysql-linux_8:
    needs: [ tests-mysql-linux ]
    uses: ./.github/workflows/tests-mysql-linux.yml
    with:
      mysql: "8.0"
      python-versions: '["3.12", "3.13", "3.14"]'
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}

  tests-mariadb-linux-11:
    needs: [ tests-mysql-linux ]
    uses: ./.github/workflows/tests-mariadb-linux.yml
    with:
      mariadb: "11.4"
      python-versions: '["3.12", "3.13", "3.14"]'
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}

  tests-mariadb-linux-10_11:
    needs: [ tests-mariadb-linux-11 ]
    uses: ./.github/workflows/tests-mariadb-linux.yml
    with:
      mariadb: 10.11
      python-versions: '["3.13", "3.14"]'
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}

  tests-oldest:
    needs: [ tests-mariadb-linux-11 ]
    uses: ./.github/workflows/tests-oldest.yml
    with:
      python-versions: '["3.10", "3.14"]'
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}

  tests-macosx:
    needs: [tests-mysql-linux]
    uses: ./.github/workflows/tests-macosx.yml
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
